### ISSUE TITLE
You become slow when you rejoin the same gameserver after dying

### ISSUE THREAD

**Issue by dotthefox** [kem0x/raider3.5#11]
Expected Behavior
Your walk speed should be the same

Current Behavior
You are slow

Steps to Reproduce

Join or host a match

Find a way to die

Rejoin the match

You will notice that your walk speed is super slow

**Comment by NickB-30** [comment]
This happens on every game server you have to change your name before you rejoin

**Comment by samuelsiv** [comment]
I will add a fix for it which is to not let anyone join after starting bus.

**Comment by Milxnor** [comment]
I believe this is something with the PlayerId

**Comment by kem0x** [comment]
This is unintended behavior, old seasons are not designed to support rejoining.
