### ISSUE TITLE
The Game Crashes 20 seconds into the loading screen

### ISSUE THREAD

**Issue by PurpleHatDev** [kem0x/raider3.5#13]
Every time I try to host the game crashes on the loading screen for no reason at all I cant even join myself because the game crashes before I can even join please help.

**Comment by GDBOI101** [comment]
Its the ban system go into \FortniteGame\Binaries\Win64 and create a blank file named banned-ips.json

**Comment by PurpleHatDev** [comment]
Thank you it works now
