### ISSUE TITLE
When your teammate dies, their HP doesn't change in the corner, and Stays 100 Whites and 100 Sheild.

### ISSUE THREAD

**Issue by LunarTuna** [kem0x/raider3.5#27]
![image](https://user-images.githubusercontent.com/94589643/174532660-ae572fda-fa3e-4b12-ac2f-82521d5e03dc.png)

**Comment by AveryMadness** [comment]
iirc just an update issue, should be an easy fix

**Comment by Jurij15** [comment]
Is that even important?

**Comment by LunarTuna** [comment]
Idk how do code lmao> iirc just an update issue, should be an easy fix
