### ISSUE TITLE
Jumping out of Bus causes server to freeze, then ping goes to 200 + ping.

### ISSUE THREAD

**Issue by LunarTuna** [kem0x/raider3.5#29]

**Comment by Jurij15** [comment]
It might be your pc issue, jumping from bus works fine for me.

**Comment by Milxnor** [comment]
I believe this only happens with the first player who jumps, if we switch to calling InitPawn or the same function as battle bus jumping whenever someone joins then it will be fixed.

**Comment by LunarTuna** [comment]
Ok don't know how to do that lol > I believe this only happens with the first player who jumps, if we switch to calling InitPawn or the same function as battle bus jumping whenever someone joins then it will be fixed.
