### ISSUE TITLE
Possibly change deafult GameMode to Solos instead of it being Duos.   

### ISSUE THREAD

**Issue by LunarTuna** [kem0x/raider3.5#30]

**Comment by samuelsiv** [comment]
Can you please refrain from making issues that can be easily resolved by taking a look at the code yourself?

**Comment by LunarTuna** [comment]
Don't know how to code buddy. > Can you please refrain from making issues that can be easily resolved by taking a look at the code yourself?

**Comment by samuelsiv** [comment]
Not our issue.
