### ISSUE TITLE
Stairs breaking on its own while building up

### ISSUE THREAD

**Issue by NickB301** [kem0x/raider3.5#4]
**Expected Behavior**
- The Stairs build normally without breaking

**Current Behavior**
- The stairs breaks by itself while building up 

**Steps to Reproduce**

-  Join or host a match

-  Sprint while building ramps

- It doesn't happen all the time im not exactly sure what causes it

**Comment by mlodyskiny** [comment]
me and my friends dont have any issues with that, are you building the source or using the binary on releases?

**Comment by Kyiro** [comment]
Fixed by #87.
