### ISSUE TITLE
My friends cant join my hamachi server

### ISSUE THREAD

**Issue by PurpleHatDev** [kem0x/raider3.5#50]
Every time I try to host I send my friends my hamachi ip and every time they try to load in they just stays on the loading screen for like 30 seconds then they are sent back to the lobby the same thing happens if I try to join my friends please help I just want to play with my friends.

**Comment by jwhazy** [comment]
Not a Raider issue. Only thing I could suggest is making sure your firewall is set up properly.

**Comment by Zacknumber2** [comment]
That worked thank you so much sorry for bothering you guys I really appreciate the help you guys are offering.
