### ISSUE TITLE
win game on spawn island

### ISSUE THREAD

**Issue by Milxnor** [kem0x/raider3.5#71]
you can win on spawn island if everyone leaves besides you, just check if bus started then make the player win.

**Comment by ramok0** [comment]
fixed here i think https://github.com/kem0x/raider3.5/commit/60c3bb2236626f2b101be15766f2e7790b0bea8c

**Comment by Kyiro** [comment]
> fixed here i think [60c3bb2](https://github.com/kem0x/raider3.5/commit/60c3bb2236626f2b101be15766f2e7790b0bea8c)

That's true, I'm closing this issue
