### ISSUE TITLE
damage is displayed twice

### ISSUE THREAD

**Issue by Duo-Vox** [kem0x/raider3.5#75]
when you shoot someone, you see twice the damage
![F093F811-C0EC-4B33-9E58-46BC0EAF05D9](https://user-images.githubusercontent.com/91671501/177059414-e847b0f0-e73d-4e46-a934-1dc4733ed01d.jpeg)

**Comment by kem0x** [comment]
oh my god can you stop making an issue about every single thing you see?? we are already aware of everything lmao.

**Comment by Duo-Vox** [comment]
oh sorry
